FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN useradd --system --no-create-home appuser
COPY piri /usr/bin/piri
USER appuser
ENTRYPOINT ["/usr/bin/piri"]
