name: Go Test

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: ipdxco/unified-github-workflows/.github/workflows/go-test.yml@v1.0
    with:
      go-versions: '["this"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e-test:
    needs: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run e2e tests
        run: go test -v -tags e2e -timeout 30m ./smelt-tests/...